name: Flutter CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          cache: true

      # 4️⃣ Flutter Doctor
      - name: Flutter Doctor
        run: flutter doctor -v

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6️⃣ Analyze code
      - name: Run analyzer
        run: flutter analyze || true

      # 7️⃣ Run tests
      - name: Run tests
        run: flutter test || true

      # 8️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release

      # 9️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 🔟 Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          name: Release v1.${{ github.run_number }}
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}